name: Run Backend Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./Backend
        run: npm install

      - name: Run unit tests
        working-directory: ./Backend
        run: npm run test:unit

      - name: Start backend server
        working-directory: ./Backend
        run: npm start &

      - name: Wait for server to be ready
        run: |
          for i in {1..10}; do
            if nc -z localhost 3000; then
              echo "Server is up!"
              break
            fi
            echo "Waiting for server..."
            sleep 3
          done
        shell: bash

      - name: Run integration tests
        working-directory: ./Backend
        run: npm run test:integration
